export const fundTags = [
  { id: '0', name: 'light-fund', auto: true },
  { id: '1', name: 'no-governance', auto: true },
  { id: '2', name: 'multisig', auto: true },
  { id: '3', name: 'instant-withdraw', auto: false },
  { id: '4', name: 'time-locked', auto: false },
  { id: '5', name: 'democratic', auto: false },
  { id: '6', name: 'treasury', auto: false },
  { id: '7', name: 'investment', auto: false },
  { id: '8', name: 'dao', auto: false },
  { id: '9', name: 'defi', auto: false },
  { id: '10', name: 'yield-farming', auto: false },
  { id: '11', name: 'staking', auto: false },
  { id: '12', name: 'nft', auto: false },
  { id: '13', name: 'gaming', auto: false },
  { id: '14', name: 'social', auto: false },
  { id: '15', name: 'charity', auto: false },
  { id: '16', name: 'research', auto: false },
  { id: '17', name: 'education', auto: false },
  { id: '18', name: 'privacy', auto: false },
  { id: '19', name: 'cross-chain', auto: false },
  { id: '20', name: 'layer2', auto: false },
  { id: '21', name: 'experimental', auto: false },
  { id: '22', name: 'stable', auto: false },
  { id: '23', name: 'high-risk', auto: false },
  { id: '24', name: 'low-risk', auto: false },
  { id: '25', name: 'long-term', auto: false },
  { id: '26', name: 'short-term', auto: false },
  { id: '27', name: 'automated', auto: false },
  { id: '28', name: 'manual', auto: false },
  { id: '29', name: 'transparent', auto: false },
  { id: '30', name: 'private', auto: false },
  { id: '31', name: 'community', auto: false }
];

